apiVersion: v1
kind: ServiceAccount
metadata:
  name: recurring-service
  namespace: default
  labels:
    app: {{ .Chart.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recurring-service-secrets
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recurring-service-secrets-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: recurring-service
  namespace: default
roleRef:
  kind: Role
  name: recurring-service-secrets
  apiGroup: rbac.authorization.k8s.io
